name = "twitter-video-downloader"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "VIDEOS"
bucket_name = "twitter-videos"
preview_bucket_name = "twitter-videos-preview"

[[d1_databases]]
binding = "DB"
database_name = "twitter_videos_db"
database_id = "your-database-id"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[vars]
# Add your environment variables here
R2_PUBLIC_URL = "https://your-custom-domain.com"
# or use: R2_PUBLIC_URL = "https://pub-YOUR_ACCOUNT_ID.r2.dev"

[env.production]
name = "twitter-video-downloader"

[[env.production.d1_databases]]
binding = "DB"
database_name = "twitter-reels-db"
database_id = "750ee1d3-c1fd-4b1e-953d-b4295b17003c"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "4e8e32b2971b43ef836b8ac7c4e9a96b"

[[env.production.r2_buckets]]
binding = "VIDEOS"
bucket_name = "twitter-videos-storage" 