name = "twitter-video-downloader"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# D1 Database binding (root level for CLI access)
[[d1_databases]]
binding = "DB"
database_name = "twitter-reels-db"
database_id = "750ee1d3-c1fd-4b1e-953d-b4295b17003c"

# KV Namespace binding (root level for CLI access)
[[kv_namespaces]]
binding = "CACHE"
id = "4e8e32b2971b43ef836b8ac7c4e9a96b"

# R2 Bucket binding (root level for CLI access)
[[r2_buckets]]
binding = "VIDEOS"
bucket_name = "twitter-videos-storage"

# Environment configuration
[env.production]
compatibility_date = "2024-01-01"

# D1 Database binding
[[env.production.d1_databases]]
binding = "DB"
database_name = "twitter-reels-db"
database_id = "750ee1d3-c1fd-4b1e-953d-b4295b17003c"

# R2 Storage binding
[[env.production.r2_buckets]]
binding = "VIDEOS"
bucket_name = "twitter-videos-storage"

# KV Storage binding for caching
[[env.production.kv_namespaces]]
binding = "CACHE"
id = "4e8e32b2971b43ef836b8ac7c4e9a96b"

# Environment variables
[env.production.vars]
ENVIRONMENT = "production"

# Preview environment (for testing)
[env.preview]
compatibility_date = "2024-01-01"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "twitter-reels-db-preview"
database_id = "your-preview-d1-database-id" # Replace with preview D1 database ID

[[env.preview.r2_buckets]]
binding = "VIDEOS"
bucket_name = "twitter-videos-storage-preview"

[[env.preview.kv_namespaces]]
binding = "CACHE"
id = "your-preview-kv-namespace-id" # Replace with preview KV namespace ID

[env.preview.vars]
ENVIRONMENT = "preview"

# Note: Cron triggers will be configured separately in Cloudflare Pages
# They are not supported in wrangler.toml for Pages projects 